### ISSUE TITLE
 gh-issues for group comms? setting hash tags, forwarding emails?

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine-ops#22]
I propose that we use gh-issues as our main group communication platform.  However, we need to be able to communicate with new members who arent familiar yet with gh.  Therefore, I propose we integrate other mediums like email, GGroups, G+, or even Twitter through the use of forwarding and careful definition of hashtags.
     
    It may even be possible to use a pub-sub format called MQTT that Ive been using for location and home automation services.  In MQTT the toughest part is in the beginning when you set up the subject tree, as you need to ensure the heirarchy is relevant and not arbitrary.

   Perhaps we can set up an online mini-hack-athon with core team members to set up a subject (hashtag) tree?

**Comment by powellc** [comment]
I'm gonna close this task and encourage us to use iterate on the initiation packet as our go-to source for communication plans.
